// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrcdicunifmszgyqktex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yY2RpY3VuaWZtc3pneXFrdGV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjEyNjAsImV4cCI6MjA2NDQ5NzI2MH0.nlLRAAJHoInqmS_JB_HTlP5AsKg778fHUm---GpPSQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);